on: [push]

env:
  node-version: 14.x

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Install libtool
        run: sudo apt install autoconf libtool

      - name: Install Madlib
        run: npm install -g @madlib-lang/madlib

      - name: Display Madlib version
        run: madlib -v

      - name: Install dependencies
        run: madlib install

      - run: ls -l lib/lib

      - name: Run tests
        run: madlib test --target llvm --coverage

      - name: Push coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .coverage/lcov.info
